[package]
name = "rs-gpio"
version = "0.1.0"
edition = "2024"

[features]
default = ["gpio_tests", "dma"]
gpio_tests = []
dma = []

[dependencies]
apigpio = "1.0.1"
ctrlc = "3.4.7"
futures = "0.3.31"
memmap2 = "0.9.7"
